Load Webfonts
unic/darvin-boilerplate pull request #11
Opened 2019-05-15 07:57 UTC by neno

2019-05-15 07:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unic/darvin-boilerplate?pullRequest=11) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unic/darvin-boilerplate?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unic/darvin-boilerplate?pullRequest=11) it.</sub>

2019-05-16 15:11 UTC, kuschti requested changes

2019-05-16 15:11 UTC, kuschti commented on src/templates/layouts/l02-webfonts/l02-index.njk
> +          script.src = "https://cdnjs.cloudflare.com/ajax/libs/fontfaceobserver/2.0.7/fontfaceobserver.js";
2.0.7 ist veraltet (von 2016), aktuell ist 2.1.0

2019-05-16 15:11 UTC, kuschti commented on src/styles/settings/_settings.scss
> +$font-1: 'OpenSansBold', Times, serif !default;
müsste hier nicht die Merriweather angegeben werden?

2019-05-23 06:04 UTC, neno commented on src/styles/settings/_settings.scss
> +$font-1: 'OpenSansBold', Times, serif !default;
Hab's auf den initial value zurückgesetzt, weil die Schriften im _fonts.scss definiert werden

2019-05-23 06:23 UTC, kuschti commented on src/styles/settings/_settings.scss
> +$font-1: 'OpenSansBold', Times, serif !default;
sollte dann im fonts.scss nicht diese Variable genutzt werden?

2019-06-03 11:51 UTC, kuschti approved these changes

2020-05-27 12:43 UTC, closed without merging